### ISSUE TITLE
Example not working in meteor 0.9.4

### ISSUE THREAD

**Issue by radiegtya** [Urigo/meteor-ionic#16]
Hi There,

I am trying to running the example but it's not working.
I am getting error like this, when creating a new project:

```
TypeError: undefined is not a function
    at createProject (http://localhost:3000/ionic.js?02a9c004d9e8246990904d3f641cf7b8b5c1bbcd:20:25)
```

and this is the error detail:

```
 $scope.Projects.add(newProject); <-- THIS IS UNDEFINED (add)
```

Please Help, Thanks :)
